import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>nav bar header
          <ul>
            <li>homepage</li>
            <li><a href="/launchsites">launchsites</a></li>
            <li><a href="/about">about</a></li>
          </ul>
        </div>
        {children}
      </body>
    </html>
  )
}
